pipeline {
    agent {
        any {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    environment {
        SONARQUBE_SERVER = 'http://3.109.143.45:9000'
        SONARQUBE_TOKEN = 'squ_40134d935a95c3f8cf791efe89c544bd99aa90da'
    }
    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs() // Clean up workspace
            }
        }
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Rakesh9731/maven-pro9731.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean compile -DskipTests'
            }
        }
        stage('SonarQube Analysis') {
            steps {
                script {
                    withSonarQubeEnv('SonarQube1') {
                        sh """
                        mvn sonar:sonar \
                            -Dsonar.projectKey=my-app \
                            -Dsonar.host.url=$SONARQUBE_SERVER \
                            -Dsonar.login=$SONARQUBE_TOKEN
                        """
                    }
                }
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
    post {
        success {
            echo "Pipeline executed successfully!"
        }
        failure {
            echo "Pipeline failed. Please check the logs."
        }
    }
}
